CREATE TABLE zdocentes AS SELECT * FROM GTD10.docentes;
ALTER TABLE zdocentes ADD PRIMARY KEY ("NR");
CREATE INDEX IDX_NOME_DOCENTE ON zdocentes("NOME");

CREATE TABLE zucs AS SELECT * FROM GTD10.ucs;
ALTER TABLE zucs ADD PRIMARY KEY ("CODIGO");
CREATE INDEX IDX_DESIGNACAO_UC ON zucs("DESIGNACAO");
CREATE INDEX IDX_CURSO_UC ON zucs("CURSO");

CREATE TABLE zocorrencias AS SELECT * FROM GTD10.ocorrencias;
ALTER TABLE zocorrencias ADD CONSTRAINT ZOCORRENCIAS_PK PRIMARY KEY("CODIGO","ANO_LETIVO", "PERIODO");
ALTER TABLE zocorrencias ADD FOREIGN KEY ("CODIGO") REFERENCES zucs("CODIGO");
CREATE INDEX IDX_DEPARTAMENTO_OCORRENCIA ON zocorrencias("DEPARTAMENTO");

CREATE TABLE ztiposaula AS SELECT * FROM GTD10.tiposaula;
ALTER TABLE ztiposaula ADD PRIMARY KEY ("ID");
ALTER TABLE ztiposaula ADD FOREIGN KEY ("CODIGO", "ANO_LETIVO", "PERIODO")
REFERENCES zocorrencias("CODIGO", "ANO_LETIVO", "PERIODO");
CREATE INDEX BTREE_IDX_TIPO_AND_ANO_LETIVO_TIPOSAULA ON ztiposaula("TIPO", "ANO_LETIVO"); --BTREE
--CREATE BITMAP INDEX BITMAP_IDX_TIPO_AND_ANO_LETIVO_TIPOSAULA ON ztiposaula("TIPO", "ANO_LETIVO"); --BTREE

CREATE TABLE zdsd AS SELECT * FROM GTD10.dsd;
ALTER TABLE zdsd ADD CONSTRAINT ZDSD_PK PRIMARY KEY("NR","ID");
ALTER TABLE zdsd ADD FOREIGN KEY ("NR") REFERENCES zdocentes("NR");
ALTER TABLE zdsd ADD FOREIGN KEY ("ID") REFERENCES ztiposaula("ID");