CREATE TABLE ydocentes AS SELECT * FROM GTD10.docentes;
ALTER TABLE ydocentes ADD PRIMARY KEY ("NR");

CREATE TABLE yucs AS SELECT * FROM GTD10.ucs;
ALTER TABLE yucs ADD PRIMARY KEY ("CODIGO");

CREATE TABLE yocorrencias AS SELECT * FROM GTD10.ocorrencias;
ALTER TABLE yocorrencias ADD CONSTRAINT YOCORRENCIAS_PK PRIMARY KEY("CODIGO","ANO_LETIVO", "PERIODO");
ALTER TABLE yocorrencias ADD FOREIGN KEY ("CODIGO") REFERENCES yucs("CODIGO");

CREATE TABLE ytiposaula AS SELECT * FROM GTD10.tiposaula;
ALTER TABLE ytiposaula ADD PRIMARY KEY ("ID");
ALTER TABLE ytiposaula ADD FOREIGN KEY ("CODIGO", "ANO_LETIVO", "PERIODO")
REFERENCES yocorrencias("CODIGO", "ANO_LETIVO", "PERIODO");

CREATE TABLE ydsd AS SELECT * FROM GTD10.dsd;
ALTER TABLE ydsd ADD CONSTRAINT YDSD_PK PRIMARY KEY("NR","ID");
ALTER TABLE ydsd ADD FOREIGN KEY ("NR") REFERENCES ydocentes("NR");
ALTER TABLE ydsd ADD FOREIGN KEY ("ID") REFERENCES ytiposaula("ID");